## -*- mode: dockerfile; -*-

FROM kkholst/stat:base

MAINTAINER "Klaus Kähler Holst" klaus@holst.it


RUN 	R -q -e "install.packages(c('RcppEnsmallen'))" &&  \
	rm -Rf /tmp/* /root/.cache

RUN 	pip3 install scipy==1.3.2 numpy scikit-build pandas && \
	rm -Rf /tmp/* /root/.cache

RUN	apk add --no-cache cmake ccache ninja && \ 
	rm -Rf /tmp/* /root/.cache /var/cache/apk/*


CMD bash


