## -*- mode: dockerfile; -*-

FROM kkholst/rdbase:r_jdk

MAINTAINER "Klaus Kähler Holst" klaus@holst.it

RUN R -q -e "install.packages(c( \
'codetools', 'foreign', \
'boot', 'cluster', 'rpart', 'KernSmooth', 'MASS', 'Matrix', 'nlme', 'lme4', 'mgcv', 'survival',  \
'randomForest', 'glmnet', 'quantreg', 'mets', 'DEoptim', 'xts' \
), repos = 'https://cloud.r-project.org/')" && rm -Rf /tmp/*

CMD bash




