## -*- mode: dockerfile; -*-

FROM kkholst/stat:r

MAINTAINER "Klaus Kähler Holst" klaus@holst.it

ENV PERSISTENT_DEPS \
	python3 python3-pip

RUN	install_packages ${PERSISTENT_DEPS} && \
	pip3 install --upgrade pip setuptools && \
	rm -Rf /tmp/*

CMD bash
