## -*- mode: dockerfile; -*-

FROM kkholst/rdbase:rx_jdk

MAINTAINER "Klaus Kähler Holst" klaus@holst.it

RUN R -q -e "install.packages(c('zoo', 'xts', 'forecast', 'dplyr', 'doParallel', 'ISOweek', 'quantreg', 'RJDBC', 'RSQLite', 'RPostgreSQL', 'RPostgres'), repos = 'https://cloud.r-project.org/')" && \
rm -Rf /tmp/*

CMD R --no-save
